name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --dev

      - name: Ruff
        run: uv run ruff check .

      - name: Mypy
        run: uv run mypy .

      - name: Pytest
        run: uv run pytest
        env:
          OPENWEATHER_API_KEY: "dummy_api_key_for_ci_testing"
